

SELECT * FROM SUBJECT;

SELECT * FROM ENROL;
INSERT INTO BOOK VALUES (11, '스포츠 의학', '한솔' , 90000);	

SELECT * FROM BOOK;


INSERT INTO BOOK (BOOKID, BOOKNAME,PUBLISHER) VALUES (13, '스포츠 123', '한솔');

SELECT * FROM BOOK;

DELETE 
FROM BOOK 
WHERE PRICE IS NULL
;
COMMIT;

INSERT INTO BOOK (BOOKID, BOOKNAME, PRICE, PUBLISHER)
VALUES (13, '스포츠 123',90000, '한솔');

DELETE FROM IMPORTED_BOOK;

CREATE TABLE Imported_Book (
bookid NUMBER,
bookname VARCHAR(40),
publisher VARCHAR(40),
price NUMBER(8)
);

INSERT INTO Imported_Book VALUES(21, 'Zen Golf', 'Pearson', 12000);
INSERT INTO Imported_Book VALUES(22, 'Soccer Skills', 'Human Kinetics', 15000);


SELECT * FROM IMPORTED_BOOK;

INSERT INTO BOOK(BOOKID, BOOKNAME, PRICE, PUBLISHER)        -- BOOK 에 IMPORTED_BOOK 를 넣는다는 의미
        SELECT BOOKID, BOOKNAME, PRICE, PUBLISHER
        FROM IMPORTED_BOOK;
        
SELECT * FROM BOOK;

SELECT ABS(-283472394) , ABS(238472934) , ROUND(4.54842,2)
FROM DUAL
;

SELECT BOOKID, REPLACE(BOOKNAME,'야구','농구')      -- 이건 수정하는게 아니라 바꿔서 본다는 의미임
FROM BOOK;

SELECT * FROM CUSTOMER;

SELECT SUBSTR(NAME,1,1) "성" , COUNT(*) "인원"
FROM CUSTOMER
GROUP BY SUBSTR(NAME,1,1)
;

SELECT SYSDATE
FROM DUAL
;